#!/usr/bin/env python3
# tab2fasta
# convert table of sequences to FASTA file.
# ejr: 2022-10-12
# lmd: 2023-02-22
import fileinput
import signal

###############################################################################
### MAIN 
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_seqtable(fh)
    print_fasta(fasta)

###############################################################################
### Read seqtable filehandle into dictionary - seqtable = header\tseq
###############################################################################
def read_seqtable(fh):
    fasta = {}

    for line in fh:
        line = line.rstrip()
        fields = line.split("\t")
        fasta[fields[0]] = fields[1]

    return fasta

###############################################################################
# Print FASTA Dictionary as FASTA to STDOUT
###############################################################################
def print_fasta(fasta):
    for header in fasta:
        print(">", header, sep="")
        print(insert_newlines(fasta[header]))

###############################################################################
### Add newlines every 80 characters for FASTA formatting
###############################################################################
def insert_newlines(string, every=80):
    lines = []

    for i in range(0, len(string), every):
        lines.append(string[i:i+every])

    return '\n'.join(lines)

###############################################################################
### RUN MAIN 
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL) 
    main()