#!/usr/bin/env python3
# tab2fasta
# convert table of sequences to FASTA file.
# ejr: 2022-10-12
# lmd: 2023-02-22
import fileinput
import signal

###############################################################################
### MAIN 
###############################################################################
def main():
    fh = fileinput.input()

    for line in fh:
        line = line.rstrip()
        fields = line.split("\t")
        print(">", fields[0], sep="")
        print(insert_newlines(fields[1]))
    
    exit(0)

###############################################################################
### Add newlines every 80 characters for FASTA formatting
###############################################################################
def insert_newlines(string, every=80):
    lines = []

    for i in range(0, len(string), every):
        lines.append(string[i:i+every])

    return '\n'.join(lines)

###############################################################################
### RUN MAIN 
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL) 
    main()